set dotenv-load := true
set positional-arguments := true

run:
    cargo run

run-release:
    cargo run --release

test:
    cargo test

clippy:
    cargo +nightly clippy --all --all-features -- -D warnings

fmt:
    cargo +nightly fmt --all -- --check